version: 2
updates:
  # Cập nhật các phụ thuộc Flutter
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "flutter"
    reviewers:
      - "your-flutter-maintainer-username"

  # Cập nhật các phụ thuộc GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "your-github-actions-maintainer-username"
